### ISSUE TITLE
请问数据库在哪 管理员账户是多少？

### ISSUE THREAD

**Issue by Noirroses** [MuYunyun/movie_demo#1]
请问数据库在哪 管理员账户是多少？

**Comment by MuYunyun** [comment]
你好，因为该项目的数据量比较大，所以没开放管理员账号。如果你想使用该项目，你可以下载到本地，通过gulp命令跑起该项目，然后你可以注册任意一个账户，通过mongo命令:db.users.update({name:’这里写你注册的账号名’},{$set:{role:100}})，你注册的这个账号就是管理员账号了。至于数据库，代码里提供了自动(爬虫)录入和手动录入两种方式，你登上管理员账号就可以通过自动录制方式也可以从微信端快速录入自己喜欢的电影和音乐。
